Use `metric` tag conditionally during wildcard query
zalando-zmon/kairosdb pull request #129
Opened 2019-11-12 12:27 UTC by rajatparida86

Use `metric` tag conditionally during wildcard query

2019-11-12 12:42 UTC, alexkorotkikh requested changes
While I don't have many questions to implementation, I wonder if the feature actually is well analyzed. I afraid that kind of query modification can result in changing the behavior, which we better have to avoid.
Example (from [this graph](https://grafana.zalando.net/d/AH6tWJIZz/coast-checkout-gateway?orgId=1&refresh=1m&fullscreen&edit&panelId=66)): query `key=[timers.zmon.response.*.GET.controllers.CheckoutController.getCheckouts.m1_rate]` would be replaced with query `metric=[m1_rate]` which has a different semantic - it would collect data points for *all* Controllers and *all* methods of this application, not only for `CheckoutController::getCheckouts`, but also for `AddressController::getAddresses` and others.
I believe that's not how ZMON is expected to behave. Let's clarify that separately.

2019-11-12 12:42 UTC, alexkorotkikh commented on src/main/java/org/kairosdb/datastore/cassandra/CassandraDatastore.java
> +            if (splitIndex.getSplitIndexField() != null && !"".equals(splitIndex.getSplitIndexField()) && splitIndex.getSplitIndexValues().size() > 0) {
I'd introduce a method for it, e.g. `splitIndex.isDefined()`

2019-11-12 16:17 UTC, tfrauenstein commented
Editorial: We called this tuning feature 'auto completion of metric tag filter for queries' -- and we should use this name consistently also for the PR. 

More important: It is IMO too early for implementation. My expectation was that we write a short Tuning Feature Solution paper, where the major open questions we discussed are answered. From implementation design point of view, my expectation was that we do not change the core code for query processing (like proposed here), but execute query auto-completion isolated, before query processing is called. 

@alexkorotkikh With respect to your example: Yes, replacing of query "key=[timers.zmon.response.*.GET.controllers.CheckoutController.getCheckouts.m1_rate]"  by query "metric=[m1_rate]" would change the semantics. But this was not the idea. It is 'auto completion of metric tag filter' i.e. query replaced by query "key=[timers.zmon.response.*.GET.controllers.CheckoutController.getCheckouts.m1_rate], metric=[m1_rate]". This query should have the same semantic, but is more efficient due to metric split index usage by query processing.

2019-11-19 09:26 UTC, alex-on-java commented
Correct me if I'm wrong, but I guess we have another PR, and this is not used anymore.

2019-11-19 09:26 UTC, closed without merging