add logging for cache cleanup
zalando-zmon/kairosdb pull request #145
Opened 2019-12-24 11:26 UTC by alex-on-java

The issue is that at some point the cache directory is not cleaned up and the disk usage starts growing

2019-12-24 11:43 UTC, pitr requested changes
1 extra ask

2019-12-24 11:43 UTC, pitr commented on src/main/java/org/kairosdb/core/datastore/KairosDatastore.java
>  	@SuppressWarnings("ResultOfMethodCallIgnored")
could you also remove `ResultOfMethodCallIgnored` and add checks that all `File.delete` calls actually return true (`logger.error` otherwise)

2019-12-24 13:39 UTC, pitr commented
:+1:

2019-12-27 09:35 UTC, alex-on-java commented
👍

2019-12-27 09:36 UTC, pitr approved these changes

2019-12-27 09:36 UTC, pitr commented
:+1:

2019-12-27 09:36 UTC, alex-on-java commented
👍

2019-12-27 09:36 UTC, merged