Adding reporting metric for datapoints requested via http endpoint
zalando-zmon/kairosdb pull request #73
Opened 2018-12-28 15:52 UTC by vibhory2j

Adding reporting metric for datapoints requested via http endpoint. The metric can be queried as `kairosdb.http.datapoints_requested`.

2018-12-28 15:53 UTC, vibhory2j commented
Addresses #71

2018-12-28 16:26 UTC, vibhory2j commented
Tested on staging and seems to be working fine.

2019-01-02 09:55 UTC, rajatparida86 requested changes

2019-01-02 09:55 UTC, rajatparida86 commented on src/main/java/org/kairosdb/core/http/rest/MetricsResource.java
> +		if (count == 0){
Anyways you are going to add the `dpsRequestedCount` irrespective of `count` So you can replace with:
```
ret.add(dpsRequestedCount);
	if (count != 0){
 			ret.add(dpsCount);
 			ret.add(dpsTime);
 	}
	return ret;
```

2019-01-02 10:26 UTC, rajatparida86 approved these changes

2019-01-02 10:26 UTC, rajatparida86 commented
👍

2019-01-02 10:26 UTC, vibhory2j commented
👍

2019-01-02 10:27 UTC, merged